export enum ControlType {
  Address = "Address",
  Autocomplete = "Autocomplete",
  DateTime = "DateTime",
  DateTimePicker = "DateTimePicker",
  Dropdown = "Dropdown",
  Formula = "Formula", 
  Mirror = "Mirror",
  Handwriting = "Handwriting",
  Input = "Input", 
  Label = "Label",
  MultiDateTime = "MultiDateTime",
  MultiDateTimePicker = "MultiDateTimePicker",
  MultiDropdown = "MultiDropdown",
  NumericInput = "NumericInput",
  Photo = "Photo",
  Scanner = "Scanner", 
  SlideToggle = "SlideToggle", 
  TextArea = "TextArea",
  TimePicker = "Time", 
  Timestamp = "Timestamp",
  EmailBox = "EmailBox",
  ObjectCounter = "ObjectCounter"
}